### PR TITLE
Make it possible to publish packages under dotkomonline on NPM

### PR DESCRIPTION
**Pull request by matsjla**
Renames the package.json organization names from `@dotkom` to `@dotkomonline` to match our organization on npm.

Also explicitly marks all packages as private or not to prevent accidental publishing of apps/other packages

### CODE REVIEW

**Comment by kharann** [comment]
Can you rebase and make sure the new updates are correct?

**Comment by matsjla** [comment]
Rebased <3

**Comment by kharann** [comment]
Have you checked if there's any instances of @dotkom/ui after rebasing? Last pull request removed the usage stitches from @theme and switched to @dotkom/ui

**Comment by matsjla** [comment]
Unless my editor's search feature scammed me it should be all good

**Review by kharann — APPROVED** [review]

**Pull request merged**
