### PR TITLE
DOT-310 Replace storybook with ladle

### PR DESCRIPTION
**Pull request by kharann**
idk maybe storybook is just too big

### CODE REVIEW

**Review by junlarsen — COMMENTED** [review]
Interesting, what are the benefits/drawbacks vs storybook?

**Comment by junlarsen** [comment]
oh its kinda hot https://ladle.dev/docs/

**Comment by kharann** [comment]
> Interesting, what are the benefits/drawbacks vs storybook?

like 20x smaller. fast af

image

we don't really use any of these features

**Comment by kharann** [comment]
We could eventually consider having the stories in a stories folder instead of inside each package in UI :thinking:

**Review by junlarsen — APPROVED** [review]

**Pull request merged**
