### PR TITLE
:sparkles: Use react-hot-toast to pop up toast

### PR DESCRIPTION
**Pull request by Thomhas**
Closes: #160 

## Changelog
- Use react-hot-toast to be able to call toasts from all places. 

## How to test

Test toast component in storybook.

### CODE REVIEW

**Comment by kharann** [comment]
IS THIS DONE

**Comment by kharann** [comment]
Convert this to Dark mode

**Comment by kharann** [comment]
Or actually, maybe use the one from radix

**Comment by Thomhas** [comment]
I will close this PR because of inactivity 😿

**Pull request closed without merging**
